{% set version = "1.0.6" %}

package:
  name: intern
  version: {{ version }}

source:
  url: https://github.com/jhuapl-boss/intern/archive/v{{ version }}.tar.gz
  sha256: 880f0c37eec2e5580f401e8da13cbe16b272d6eb34efa23e947951ce6d6debae

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - requests >=2.11.1
    - python-blosc >=1.4.4
    - six
    - numpy
    - zmesh

test:

# We can't run the full test suite without boss credentials,
# so we don't bother with these for now
#  requires:
#    - mock
#    - nose2

  imports:
    - intern
    - intern.remote.boss.remote
    - intern.resource.boss.resource
    - intern.service.boss.service
    - intern.utils.parallel

about:
  home: https://github.com/jhuapl-boss/intern
  license: Apache-2.0
  license_file: license
  summary: 'Python 2/3 SDK for interacting with the Boss REST API '

extra:
  recipe-maintainers:
    - jtpdowns
    - stuarteberg
