{% set version = "1.4.2" %}

package:
  name: intern
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/intern/intern-{{ version }}.tar.gz
  sha256: 63ebeb114e5f5ae714255327d9f80a8af4ec354c8375b0468c5b1131952dce6a

build:
  number: 0
  script:
    - sed -i.bak '/^nose2$/d' requirements.txt
    - {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.11.1
    - python-blosc >=1.4.4
    - six
    - numpy
    - zmesh
    - psutil
    - pillow
    - tqdm
    - joblib

test:

# We can't run the full test suite without boss credentials,
# so we don't bother with these for now
#  requires:
#    - mock
#    - nose2

  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - intern
    - intern.remote.boss.remote
    - intern.resource.boss.resource
    - intern.service.boss.service
    - intern.utils.parallel

about:
  home: https://github.com/jhuapl-boss/intern
  license: Apache-2.0
  license_file: license
  summary: 'Python 2/3 SDK for interacting with the Boss REST API '

extra:
  recipe-maintainers:
    - j6k4m8
    - dxenes1
    - sandyhider
    - movestill
    - jtpdowns
    - stuarteberg
